### ISSUE TITLE
postmaterial asset

### ISSUE THREAD

**Issue by PascalSoftwares** [CthulhuBaba/LiteWater#2]
With basic setup tutorial, log gives some missing assignment of Water material instance, which meant to be 'Postmaterial'.

```
[ 00:00:16.040 ]: [Warning] Exception has been thrown. Object reference not set to an instance of an object.
Stack strace:
   at Game.Water.OnFixedUpdate() in Y:\HyperTactics\Source\Game\ThirdParty\LiteWaterSource\Water.cs:line 71
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerNoRet0`1.InvokeThunk(Object delegateContext, ManagedHandle instancePtr, IntPtr* paramPtrs) in F:\FlaxEngine\Source\Engine\Engine\NativeInterop.Invoker.cs:line 223
   at FlaxEngine.Interop.NativeInterop.ThunkContext.InvokeThunk(ManagedHandle instanceHandle, IntPtr param1, IntPtr param2, IntPtr param3, IntPtr param4, IntPtr param5, IntPtr param6, IntPtr param7) in F:\FlaxEngine\Source\Engine\Engine\NativeInterop.cs:line 1226
[ 00:00:16.040 ]: [Warning] Exception has been thrown.
Object reference not set to an instance of an object.
```

Postmaterial asset assignment is not covered in tutorial. water works fine without it, but exception messages are flooded in log window.
Is there any appropriate material asset included in repository?

**Comment by CthulhuBaba** [comment]
Thanks for reporting this.

In the water script, there are post material and fog options for the underwater effect. Like in this picture;
![underwater](https://github.com/CthulhuBaba/LiteWater/assets/31192693/b79b5239-0d5d-4f81-b692-b43db8de5230)

There is even a skybox option to determine the sun angle.

I didn't add them to the repository. Honestly, I forgot to delete those options/codes. You can delete them in "Water.cs".

I will fix it in the future,  (Maybe I will delete those options or upload the relevant content.)  but I cannot update it right now because I do not have the opportunity.

**Comment by CthulhuBaba** [comment]
I uploaded an old project. You can import the post material and others into your project if you wish.
[https://drive.google.com/file/d/1NkF9O4tEQczuWqnbyyUa5M6StFSD6Q_y/view?usp=sharing](https://drive.google.com/file/d/1NkF9O4tEQczuWqnbyyUa5M6StFSD6Q_y/view?usp=sharing)
